#define CHAMBER_TWO_IN_TIME 2
#define FRESH_MEDIA_IN_TIME_UPON_CHAMBER_TWO 2
#define CARBON_DIOXIDE_TO_TOTAL_PERCENTAGE 2
#define TOTAL_GAS_IN_TIME_UPON_CHAMBER_TWO 2
#define CARBON_DIOXIDE_IN_TIME_UPON_CHAMBER_TWO \
        TOTAL_GAS_IN_TIME_UPON_CHAMBER_TWO * CARBON_DIOXIDE_TO_TOTAL_PERCENTAGE
#define NITROGEN_IN_TIME_UPON_CHAMBER_TWO \
        TOTAL_GAS_IN_TIME_UPON_CHAMBER_TWO * (1 - CARBON_DIOXIDE_TO_TOTAL_PERCENTAGE)
#define CHECKPOINT_INTERVAL {1,2,3,4,5,6}
#define WASTE_MEDIA_OUT_TIME 
#define FRESH_MEDIA_IN_TIME 
#define TOTAL_GAS_IN_TIME
#define CARBON_DIOXIDE_IN_TIME \
        TOTAL_GAS_IN_TIME * CARBON_DIOXIDE_TO_TOTAL_PERCENTAGE
#define NITROGEN_IN_TIME \
        TOTAL_GAS_IN_TIME * (1 - CARBON_DIOXIDE_TO_TOTAL_PERCENTAGE)

#define MOTOR_CHIP_ONE_PMMA_A 2
#define MOTOR_CHIP_ONE_PMMA_B 2
#define MOTOR_CHIP_ONE_INPUT_A_ONE 2
#define MOTOR_CHIP_ONE_INPUT_A_TWO 2
#define MOTOR_CHIP_ONE_INPUT_B_ONE 2
#define MOTOR_CHIP_ONE_INPUT_B_TWO 2
#define MOTOR_CHIP_TWO_PMMA_A 2
#define MOTOR_CHIP_TWO_PMMA_B 2
#define MOTOR_CHIP_TWO_INPUT_A_ONE 2
#define MOTOR_CHIP_TWO_INPUT_A_TWO 2
#define MOTOR_CHIP_TWO_INPUT_B_ONE 2
#define MOTOR_CHIP_TWO_INPUT_B_TWO 2
#define NITROGEN_RELAY 2
#define CARBON_DIOXIDE_RELAY 2


void setup() {
    pinMode(MOTOR_CHIP_ONE_PMMA_A, OUTPUT);
    pinMode(MOTOR_CHIP_ONE_PMMA_B, OUTPUT);
}

void loop(){
    
}